#!/bin/bash

# Components of Toolbag are installed in /usr/local/bin
# because this is generally on the path and rarely used.  

	destbin=/usr/local/bin
	destserv=/lib/systemd/system

	if [ ! -d "$destbin" ]; then 	
		echo "'$destbin' folder missing, I cannot proceed"		
		exit
	elif [ ! -d "$destserv" ]; then 	
		echo "'$destserv' folder missing, I cannot proceed"		
		exit
	elif [ ! -x "$(command -v wget)" ]; then
		echo "wget command missing, I cannot proceed"		
		exit
	elif [ ! -x "$(command -v tar)" ]; then	
		echo "tar command missing, I cannot proceed"		
		exit
	fi

	# Make temp
	if [ -d ~/temp ]; then
		echo "~/temp already exists. Delete it before running this"
		exit	
	fi  
	mkdir ~/temp	
	cd ~/temp 
	
	# Next line is updated upon release 
	VERSION
	source="https://github.com/julianpratt/Toolbag/releases/download/$version" 
	
	# Install scripts   	
	wget $source/scripts.tar.gz
	tar xvzf scripts.tar.gz
	rm scripts.tar.gz
	chmod 777 *	# scripts, etc come down from github without the execute permission set 
	sudo chown root:root * 
	sudo mv * $destbin
	
	# Clean up
	cd ~
	sudo rm -rf temp
	
	# Install Nala (https://manual.siduction.org/sys-admin-nala_en.html), jq and Flatpak as standard
	sudo apt update
	sudo apt install -y nala jq curl  
	if [ ! -x "$(command -v flatpak)" ]; then
	  sudo apt install flatpak
	  sudo add-apt-repository ppa:flatpak/stable
	  flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo	
	fi  
	
	
	# Other Standard Setup
	
	# Required by Steam, but only set if on amd64  
	[ "$(uname -m)" EQ "x86_64" ] && sudo dpkg --add-architecture i386
	
	# If the keyboard layout is UK, then set the locale to UK  
	[ "$(localectl status | grep 'X11 Layout' | cut -d: -f2)" EQ " gb" ] && sudo update-locale LANG=en_GB.UTF-8 LC_TIME=en_GB.UTF-8
