#!/bin/bash
cd hub
archs=(amd64 arm arm64)
for arch in ${archs[@]}
do
	env GOOS=linux GOARCH=${arch} go build -o hub_${arch} hub.go page.go site.go
done
mv hub_arm hub_armv6l 
cd ..
gh release upload $(versions toolbag) setup hub/hub_*
rm hub/hub_* 
