#!/bin/bash

# Components of Toolbag are installed in /usr/local/bin
# because this is generally on the path and rarely used.  

	dest=/usr/local/bin
	version=v1.0

	if [ ! -d "$dest" ]; then 	
		echo "'$dest' folder missing, I cannot proceed"		
		exit
	fi

	# Make temp
	if [ -d ~/temp ]; then
		echo "~/temp already exists. Delete it before running this"
		exit	
	fi  
	mkdir ~/temp	
	cd ~/temp 
	
	# Get scripts
	wget https://github.com/julianpratt/Toolbag/archive/refs/tags/$version.tar.gz -O toolbag.tar.gz
	tar xvzf toolbag.tar.gz --strip-components=1
	if [ ! -d scripts ]; then 	
		echo "scripts folder missing from Toolbag, I cannot proceed"	
		exit
	fi	

	# Install scripts   	
	cd scripts
	chmod +x *	# scripts, etc come down from github without the execute permission set 
	sudo chown root:root * 
	sudo mv * $dest

	# Install hub
	wget https://github.com/julianpratt/Toolbag/releases/download/$version/hub_$(query arch) -O hub
	chmod +x *	# scripts, etc come down from github without the execute permission set 
	sudo chown root:root * 
	sudo mv * $dest

	# Clean up
	cd ~
	sudo rm -rf temp
	rm setup
	
