#!/bin/bash

# Components of Toolbag are installed in /usr/local/bin
# because this is generally on the path and rarely used.  
dest=/usr/local/bin

if [ ! -d Toolbag ]; then 
	echo "setup must be run from the parent of Toolbag"
elif [ ! -d Toolbag/scripts ]; then 	
	echo "scripts folder missing from Toolbag, I cannot proceed"	
elif [ ! -d "$dest" ]; then 	
	echo "'$dest' folder missing, I cannot proceed"		
else
	cd Toolbag
	# Install scripts   	
	cd scripts
	chmod +x *	# scripts come down from github without the execute permission set 
	sudo mv * $dest
	cd ../..
	rm -rf Toolbag
fi