#!/bin/bash
#
# backup - runs as a scheduled task
#
# zip options are:
#    FS - filesync (update zip with new or changed files, remove any deleted files)
#    r  - recurse into subdirectories
#    x  - exclude these (in this case hidden files/directories) 

home=/home/julian
backups=$home/Drive/Backups
log=$backups/backup-log.txt 

do-folder() { echo "Backing up $1" >> $log ; zip -FSr $backups/$1.zip $home/$1 -x .* >> $log ; }  

echo "Backup Started" > $log

do-folder Books
do-folder Dev
do-folder Documents
do-folder Mail
do-folder Photos
do-folder Publish
do-folder Trains
