#!/bin/bash
#
# backup - runs as a scheduled task
#
# zip options are:
#    FS - filesync (update zip with new or changed files, remove any deleted files)
#    r  - recurse into subdirectories
#    x  - exclude these (in this case hidden files/directories) 

fatal()     { echo "fatal: $*" >&2; exit 1; }                   # exit with message and generic error code   
pass-item() { pass-cli item view pass://Personal/Desktop/$1; }  # Get value from Proton Pass Desktop 
check-set() { [ "$1" == "" ] && fatal "$2 not set."; }          # Confirm we have values
do-folder() { echo "Zipping up $2" >> $log ; zip -FSr $1/$2.zip $home/$2 -x .*   >> $log ; }  

backups=$(pass-item backups)
remote=$(pass-item remote)
password=$(pass-item sshpass)
home=$(pass-item home)

check-set "$backups"  "backups"
check-set "$remote"   "remote"
check-set "$password" "sshpass"
check-set "$home"     "home"

log=$backups/backup-log.txt 

echo "Backup Started" > $log

for d in $(find $home -maxdepth 1 -not -path '*/.*' -type d) ; do
    if [ "$d" != "$home" ]; then
		if [ ! -z "$( ls -A $d )" ]; then
			do-folder $backups $(basename $d)
		fi	
    fi
done

sshpass -p $password rsync -utp $backups/* rsync://$remote/$(basename $backups)
