#!/bin/bash

usage() {
cat << EOF  
desktop - Will create a shortcut on the desktop to start an application.
          Usage: 'desktop command appname icon'
           e.g.   desktop panelpro "JMRI PanelPro" "/opt/JMRI/resources/PanelPro.gif"

           Use the -a option to make the application autostart 
           (it adds a link to the desktop shortcut in ~/.config/autostart)
EOF
}

autostart="no"

while getopts ah flag
do
    if [ ${flag} == "h" ]; then 
    	usage
		  exit
    elif [ ${flag} == "a" ]; then 
			autostart="yes"
			shift
    fi
done

if [ "$1" == "" ]; then	
	echo "You need to specify which command the shortcut will execute. See shortcut -h."
	exit
elif [ "$2" == "" ]; then	
	echo "You need to specify the name of the application. See shortcut -h."
	exit
elif [ "$3" == "" ]; then	
	echo "You need to specify the desktop icon. See shortcut -h."
	exit
fi

command="$1"
appname="$2"
icon="$3"

if [ ! -d ~/Desktop ]; then
		mkdir ~/Desktop
fi

cat > ~/Desktop/$command.desktop << EOF
[Desktop Entry]
Encoding=UTF-8
Name=$appname
Comment=Start $appname
Exec=$command
Icon=$icon
Terminal=false
Type=Application
X-KeepTerminal=false
StartupNotify=false
EOF

if [ "$autostart" == "yes" ]; then
	if [ ! -d ~/.config ]; then
		mkdir ~/.config
	fi	
	if [ ! -d ~/.config/autostart ]; then
		mkdir ~/.config/autostart
	fi	

	ln -s ~/Desktop/$command.desktop ~/.config/autostart/$command.desktop

fi
