#!/bin/bash

while getopts h flag
do
    if [ ${flag} == "h" ]
    then 
		echo "fetch - use FTP to download a folder from the NAS."
        echo "        Specify the volume, folder and user password, "
        echo "        thus: 'fetch volume folder password'."
        echo "        The NAS environment variable is set during bootstrap."
		exit
    fi
done

if [ "${#NAS}" == 0 ]; then
    echo "Set the NAS environment variable."
    echo "e.g. export NAS=http://mynas"
    exit
fi  

if [ "${#3}" == 0 ]; then
    echo "Password omitted, e.g. fetch volume folder password"
    exit
fi  

if [ "${#2}" == 0 ]; then
    echo "Folder omitted, e.g. fetch volume folder password"
    exit
fi  

if [ "${#1}" == 0 ]; then
    echo "Volume omitted, e.g. fetch volume folder password"
    exit
fi

if [ -f /etc/VERSION ]; then
	echo "Do not use this on a Synology"	  
	exit
fi
  

volume="$1" 
folder="$2" 
pass="$3" 

wget -r -nH ftp://$USER:$pass@$NAS/$volume/$folder
cd $volume
mv $folder ..
cd ..
rmdir $volume 
