#!/bin/bash

while getopts h flag
do
    if [ ${flag} == "h" ]; then 
			echo "getuserdata - Will output data from the GECOS field of /etc/passwd"
			echo "              Usage: 'getuserdata LOGIN FIELD'"
			echo "              where: FIELD is either 'name' or 'email'"
			echo "                     (e.g. getuserdata \$USER name)."
		exit
    fi
done

if [ "$1" == "" ]; then	
	echo "You need to specify the user. See getuserdata -h."
	exit	
fi

if [ "$2" == "name" ]; then
	getent passwd "$1" | awk -F: '{print $5}' | awk -F, '{print $1}'  
elif [ "$2" == "email" ]; then
	getent passwd "$1" | awk -F: '{print $5}' | awk -F, '{print $5}'  
else
	echo "You need to specify either 'name' or 'email'. See getuserdata -h."
fi
