#!/bin/bash

usage() {
cat << EOF  
getuserdata - Will output data from the GECOS field of /etc/passwd
              Usage: 'getuserdata LOGIN FIELD'
              where: FIELD is either 'name' or 'email'
                     (e.g. getuserdata \$USER name).
EOF
}

while getopts h flag; do
    if [ ${flag} == "h" ]; then 
    	usage
		exit
    fi
done

if [ "$1" == "" ]; then	
	echo "You need to specify the user and field ('name' or 'email'). See getuserdata -h."
	exit	
fi

if [ "$2" == "name" ]; then
	getent passwd "$1" | awk -F: '{print $5}' | awk -F, '{print $1}'  
elif [ "$2" == "email" ]; then
	getent passwd "$1" | awk -F: '{print $5}' | awk -F, '{print $5}'  
else
	echo "You need to specify either 'name' or 'email' as second parameter. See getuserdata -h."
fi
