#!/bin/bash

while getopts h flag
do
    if [ ${flag} == "h" ]
    then 
		echo "notes - Synchronise latest notes - specify drive that has secondary copy."
        echo "        e.g. 'notes j'"
		exit
    fi
done

if [ "$1" == "" ]
then
    echo "Error: Please specify drive to copy notes to."    
else
    if [ ! -d "/mnt/$1" ] 
    then
        sudo mkdir /mnt/$1
        del="yes"
    else
        del="no"    
    fi
    sudo mount -t drvfs $1: /mnt/$1
    rsync -crlpDvA --no-perms --delete --exclude=".*" /mnt/c/Users/$USER/iCloudDrive/iCloud~md~obsidian/Notes /mnt/$1    
    sudo umount $1:
    if [ "$del" == "yes" ] 
    then
        sudo rmdir /mnt/$1
    fi    
fi
