#!/bin/bash

pass-item() { pass-cli item view pass://Personal/Desktop/$1; }  # Get value from Proton Pass Desktop 
password()  { sshpass -p $(pass-item sshpass) $@; }             # Provide password for rsync


while getopts h flag
do
    if [ ${flag} == "h" ]
    then 
		echo "pull - use rclone to synchronise a folder from Drive or Dropbox."
        echo "       Drive and Dropbox must be configured as rclone remotes"
        echo "       i.e. drive: and dropbox:. Thus: 'pull remote folder',"
        echo "       expands to rclone sync remote:folder folder."
        echo "       It is assumed that the folder has the same name on both"
        echo "       remote and local filesystems." 
		echo "       If remote is omitted, then 'drive' is assumed."  	
		exit
    fi
done

if [ "${#1}" == 0 ]; then
    echo "Remote and folder omitted, e.g. pull remote folder or pull folder"
    exit
fi  

if [ -f /etc/VERSION ]; then
	echo "Do not use this on a Synology"	  
	exit
fi

if [ "${#2}" == 0 ]; then
	remote="nas" 
	folder="$1" 
else
	remote="$1" 
	folder="$2" 
fi	

if [ "$remote" == "nas" ]; then
	password rsync -ru --delete rsync://$(pass-item remote)/$1/ ~/$1
else
	rclone sync $remote:$folder $folder
fi



