#!/bin/bash

while getopts h flag
do
    if [ ${flag} == "h" ]
    then 
		echo "push - use rclone to synchronise a folder to Drive or Dropbox."
        echo "       Drive and Dropbox must be configured as rclone remotes"
        echo "       i.e. drive: and dropbox:. Thus: 'push remote folder',"
        echo "       expands to rclone sync folder remote:folder."
        echo "       It is assumed that the folder has the same name on both"
        echo "       remote and local filesystems."     
		echo "       If remote is omitted, then 'drive' is assumed."  			
		exit
    fi
done

if [ "${#1}" == 0 ]; then
    echo "Remote and folder omitted, e.g. push remote folder or push folder"
    exit
fi  

if [ "${#2}" == 0 ]; then
	remote="drive" 
	folder="$1" 
else
	remote="$1" 
	folder="$2" 
fi	

rclone sync $folder $remote:$folder
