#!/bin/bash

while getopts h flag
do
    if [ ${flag} == "h" ]
    then 
		echo "query - report on configuration and environment"
        echo "        'query ip' reports: IP address, gateway IP address and DNS IP address" 
        echo "        'query arch' reports the machine architecture (as used by golang: amd64, arm64 or armv6l)" 
		exit
    fi
done

if   [ "$1" == "ip" ]; then
    echo "IP address is $(hostname -I)"
    echo "Gateway IP address is $(ip r | grep default)"
    cat /etc/resolv.conf | grep nameserver

elif [ "$1" == "arch" ]; then
	a=$(uname -m)
	if   [ $a == "x86_64" ]; then 
		a="amd64"
	elif [ $a == "aarch64" ]; then 
		a="arm64"
	elif [ $a == "armv7l" ]; then 
		a="armv6l"
	else
		a="unknown"
	fi

	echo "$a"	

else
    echo "query '$1' is not valid."    
fi
