#!/bin/bash

fatal()     { echo "fatal: $*" >&2; exit 1; }                   # exit with message and generic error code   
pass-item() { pass-cli item view pass://Personal/Desktop/$1; }  # Get value from Proton Pass Desktop 
check-set() { [ "$1" == "" ] && fatal "$2 not set."; }          # Confirm we have values

backups=$(pass-item backups)
remote=$(pass-item remote)
password=$(pass-item sshpass)

check-set "$backups"  "backups"
check-set "$remote"   "remote"
check-set "$password" "sshpass"

cd /tmp
sshpass -p $password rsync -utp rsync://$remote/$(basename $backups)/$1.zip .
cd /
unzip -nq /tmp/$1.zip
rm /tmp/$1.zip
