#!/bin/bash

# Components of Toolbag are installed in /usr/local/bin
# because this is generally on the path and rarely used.  

	destbin=/usr/local/bin
	destserv=/lib/systemd/system

	if [ ! -d "$destbin" ]; then 	
		echo "'$destbin' folder missing, I cannot proceed"		
		exit
	elif [ ! -d "$destserv" ]; then 	
		echo "'$destserv' folder missing, I cannot proceed"		
		exit
	elif [ ! -x "$(command -v wget)" ]; then
		echo "wget command missing, I cannot proceed"		
		exit
	elif [ ! -x "$(command -v tar)" ]; then	
		echo "tar command missing, I cannot proceed"		
		exit
	fi

	# Make temp
	if [ -d ~/temp ]; then
		echo "~/temp already exists. Delete it before running this"
		exit	
	fi  
	mkdir ~/temp	
	cd ~/temp 
	
	version=$(toolbag)
	source="https://github.com/julianpratt/Toolbag/releases/download/$version" 
	
	# Install hub
	if [ "$(query arch)" == "unknown" ]; then 	
		echo "Unknown machine architecture. I cannot install hub"	
		exit
	fi	
	wget $source/hub_$(query arch) -O hub
	chmod 777 *	# executables come down from github without the execute permission set 
	sudo chown root:root * 
	sudo mv * $destbin

	# Install services   	
	if [ ! -x "$(command -v systemctl)" ]; then	
		echo "systemctl command missing, I cannot install services"		
		exit
	fi
	wget $source/services.tar.gz
	tar xvzf services.tar.gz
	rm services.tar.gz
	chmod 644 *	# permissions should be: -rw-r--r-- 
	sudo chown root:root * 
	for f in *; do
		if [ "$(systemctl is-active --quiet $f)" ]; then
			sudo systemctl stop $f
			sudo mv $f $destserv
			sudo systemctl daemon-reload
			sudo systemctl start $f
		else	
			sudo mv $f $destserv
		fi	
    done

	# Clean up
	cd ~
	sudo rm -rf temp
	