#!/bin/bash

DATE=`date '+%Y-%m-%d %H:%M:%S'`
echo "Example service started at ${DATE}" | systemd-cat -p info

while true; do
  DATE=`date '+%Y-%m-%d %H:%M:%S'`
  echo "Looping @ ${DATE}..."
  sleep 30
done