#!/bin/bash

cat << EOF  

Toolbag - tools to simplify stuff and reduce documentation

They are installed into /usr/local/bin from Toolbag by running the Toolbag/setup script. 
This is their documentation. For more information on each tool use: tool -h (e.g. versions -h).

Areas covered:
* remote storage, e.g. Drive, Dropbox and GitHub (push and pull) 
* systemd background services (makesys)
* app access (desktop and shortcut)
* file management (decrud and treesize)

addtool   - install: dotnet, java, JMRI, vscode, latex, pandoc, golang, mono, noip2 
decrud    - removes superfluous files left by Apple Finder
desktop   - create a shortcut icon on the desktop to start an application  
lowerfn   - filenames to lower case
makesys   - setup a systemd service to run a command
pull      - changes from the cloud - synchronise a folder with its master copy in the cloud
push      - changes to the cloud - synchronise a folder with its master copy in the cloud
query     - report on configuration and environment (e.g. IP address) 
setupgit  - used to setup the Dev environment
shortcut  - creates a shortcut script in /usr/local/bin to execute a command
temp      - creates or destroys a temporary folder under the user's home
tools     - this documentation
toolsinit - setup tools on a remote machine
treesize  - calculates space used by folders in current directory
update    - updates apt packages and toolbag itself 
userdata  - sets or gets the user's name and/or email (stored in the GECOS field of /etc/passwd)
versions  - reports the installed version of: git, dotnet, java, code, node, npm
	
n.b. addtool, desktop, pull, push, setupgit and userdata should not be used on a Synology NAS.	
EOF
