#!/bin/bash

while getopts h flag
do
    if [ ${flag} == "h" ]; then 
		echo "update - First gets an updated list of apt package versions and then"
		echo "         does a full upgrade of each package to its latest version."
		echo "         It then updates all the Toolbag scripts. If used with the"
		echo "         toolbag parameter (e.g. 'update toolbag'), then it just updates" 
		echo "         the Toolbag scripts and binaries. It invokes sudo itself."
		exit
    fi
done

if [ "$1" == "toolbag" ]; then
	echo "Just updating toolbag scripts and binaries"
else	
	sudo apt update
	sudo apt full-upgrade -y
fi

if   [ ! command -v git &> /dev/null ]; then
	echo "Cannot update Toolbag components, git is not available" 
elif [ ! command -v temp &> /dev/null ]; then
	echo "Cannot update Toolbag components, temp is not available" 
else
	. temp
    git clone https://github.com/julianpratt/Toolbag
    chmod +x Toolbag/setup
    Toolbag/setup
    temp untemp
fi    
