#!/bin/bash

usage() {
cat << EOF  
update - First gets an updated list of apt package versions and then
         does a full upgrade of each package to its latest version.
         It then updates all the Toolbag scripts. If used with the
         toolbag parameter (e.g. 'update toolbag'), then it just updates 
         the Toolbag scripts and binaries. It invokes sudo itself.
EOF
}

while getopts h flag
do
    if [ ${flag} == "h" ]; then 
    	usage
		exit
    fi
done

if [ "$1" == "toolbag" ]; then
	echo "Just updating toolbag scripts and binaries"
else	
	sudo apt update
	sudo apt full-upgrade -y
fi

if   [ ! command -v git &> /dev/null ]; then
	echo "Cannot update Toolbag components, git is not available" 
elif [ ! command -v temp &> /dev/null ]; then
	echo "Cannot update Toolbag components, temp is not available" 
else
	. temp
    git clone https://github.com/julianpratt/Toolbag
    chmod +x Toolbag/setup
    Toolbag/setup
    temp untemp
fi    
