#!/bin/bash

usage() {
cat << EOF  
userdata -  Will get or set data in the GECOS field of /etc/passwd

			Usage:	'userdata get LOGIN FIELD'
			where:	FIELD is either 'name' or 'email'
					e.g. userdata get \$USER name
				  
			or		'userdata set LOGIN NAME EMAIL 	
			where:	LOGIN is the login of the user
					NAME is the name of the user (i.e. first name and surname)
					EMAIL is the emal address of the user
					e.g. userdata set fred "Fred Bloggs" "fred.bloggs@gmail.com"
					
EOF
}

while getopts h flag; do
    if [ ${flag} == "h" ]; then 
    	usage
		exit
    fi
done

if [ -f /etc/VERSION ]; then
	echo "Do not use this on a Synology"	  
	exit
fi

if   [ "$1" == "get" ]; then
	if [ "$2" == "" ]; then	
		echo "Please specify the user and field ('name' or 'email'). See userdata -h."
		exit	
	fi

	if [ "$3" == "name" ]; then
		getent passwd "$2" | awk -F: '{print $5}' | awk -F, '{print $1}'  
	elif [ "$3" == "email" ]; then
		getent passwd "$2" | awk -F: '{print $5}' | awk -F, '{print $5}'  
	else
		echo "Please specify either 'name' or 'email' as second parameter. See userdata -h."
	fi	

elif [ "$1" == "set" ]; then	
	if   [ "$2" == "" ]; then	
		echo "Please specify the login of the user. See userdata -h."
	elif [ "$3" == "" ]; then	
		echo "Please specify the name of the user. See userdata -h."
	elif [ "$4" == "" ]; then	
		echo "Please specify the email address of the user. See userdata -h."
	else
		sudo chfn $2 -f "$3" -o "$4"
	fi	

else
	echo "Please specify the action ('get' or 'set'). See userdata -h."
fi
