#!/bin/bash 

while getopts h flag
do
    if [ ${flag} == "h" ]
    then 
		echo "versions - Check versions of the following installed packages and/or commands:"
		echo "           git, dotnet, java, vscode, node, npm"
		echo "           If it reports that something is not installed, then that package"
		echo "           or command can be installed using addtool (e.g. addtool dotnet)."
		exit
    fi
done

if [ "$1" == "toolbag" ]; then
	echo "v1.2"
	exit
fi 

if [ -f /etc/VERSION ]; then
	echo "This should not produce anything interesting on a Synology"	  
fi

if ! command -v git &> /dev/null
then
    echo "git is not installed"
else
	git  --version	
fi

if ! command -v dotnet &> /dev/null
then
    echo "dotnet is not installed"
else
	v=$(dotnet --info | grep "  Version")
	echo "dotnet $v"
fi

if ! command -v java &> /dev/null
then
    echo "java is not installed"
else
	java -version
fi

if ! command -v code &> /dev/null
then
    echo "vscode is not installed"
else
	v=$(code -h | grep --colour=never "^Visual Studio Code")
	echo "$v"
fi

if ! command -v node &> /dev/null
then
    echo "node is not installed"
else
	echo "node $(node -v)"	
fi

if ! command -v npm &> /dev/null
then
    echo "npm is not installed"
else
	echo "npm version $(npm -v)"	
fi
